# Site settings
title: Your awesome title
email: info@peep.com

imgs: "http://s3.amazonaws.com/peep-emails/assets"
url: "http://www.peep.com"

# imgs: "/img"

baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

# Some default styles
p: "font-size:18px; color:#292929; font-family:Arial, Helvetica, sans-serif; margin-top: 0px; margin-bottom: 0px; line-height: 30px;"
